services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - external_postgres_data:/var/lib/postgresql/data

  postgres_backup:
    build:
      context: ./backup
    container_name: postgres_backup
    restart: unless-stopped
    env_file:
    #   - ../.env
      - ./.env
    volumes:
      - ./:/app:rw
      - ./backups:/backups:rw
    depends_on:
      - postgres

volumes:
  external_postgres_data:
    external: true
